### ISSUE TITLE
MBED-OS 6 Port

### ISSUE THREAD

**Issue by saffetblt** [akiroz/ModbusMaster#2]
Hello, thanks for the project. But now MBED 6 I could not run this project. Can you please open a new branch for MBED 6?

**Comment by akiroz** [comment]
I'm aware of this issue, but since the serial API on mbed 6 is vastly different from mbed 5 I don't think I currently have the capacity to port this project to mbed 6.

Pull requests are welcome.

**Comment by akiroz** [comment]
@saffetblt mbed 6 support has been implemented in the master branch, closing this issue.
