### ISSUE TITLE
difficulty compiling due to parameters passed to write

### ISSUE THREAD

**Issue by GTNicholson** [akiroz/ModbusMaster#5]
I found your libary relating to using Modbus with the mbed.
I have tried both MBed5 and Mbed6 versions, but have trouble building in either of them.
 
        if (preTransmit) preTransmit();
            write(txBuf, txLen, [this](int e){
            attach([this](){ rxHandler(); });
            if(postTransmit) queue->call(postTransmit);
        }, SERIAL_EVENT_TX_COMPLETE);
 
 
The problem seems to be that the definition of the write call expects only two parameters, but this (line 81 in the OS6 version) Is passing 3 parameters, and the function expects two.
 
I am keen to learn how I can use Modbus peripherals and am struggling.

**Comment by akiroz** [comment]
@GTNicholson  Which version of mbed OS are you using?
This code is based on the `write` method on the SerialBase class (extended by `TransactionSerial` subclass) as documented here:
https://os.mbed.com/docs/mbed-os/v6.16/mbed-os-api-doxy/classmbed_1_1_serial_base.html#a7b3f9366101e9d01349d7bccb830d9ee

It had been tested on mbedOS 6.9 IIRC. Could you check the `SerialBase` implementation on your mbed installation?

**Comment by GTNicholson** [comment]
Very strange! I was using 6.17. It compiles fine when using mbed-os v6.16. I checked the SeriaBase and can't see what has changed with v6.17. It is also possible that I have got confused with my os versions. I will recheck with 6.17 and let you know.
In the meantime thanks I can now move forwards.
